# preload = ~/pictures/papers/apple.png
# preload = ~/pictures/papers/lucy.jpg
# preload = /home/pavelresh/pictures/papers/seeing_red.png
preload = /home/pavelresh/pictures/papers/spring_path.jpg

wallpaper = eDP-1,/home/pavelresh/pictures/papers/anime.jpeg

ipc = on
splash = false
